bullhorn/rest-api-docs

- source/includes/_subscription.md
There is a "RRequired" that has been fixed to "Required".
> Update _subscription.md Removing a double R

- source/includes/_departmententities.md
- source/includes/_myentities.md
Removed ClientCorporation and JobOrder from the list of supported entities.
> Removed ClientCorporation and JobOrder

- source/includes/entityref/_candidate.md
- source/includes/entityref/_placement.md
Update the doc to include info about our new fields that we added to Candidate and Placement entity
> BH-66743: Update doc to include info about our new fields

- source/includes/entityref/paybill/_earncode.md
- source/includes/entityref/paybill/_earncodegroup.md
- source/includes/entityref/paybill/_placementratecardline.md
- source/includes/get.md
- GET allows nested nested to-many fields
- PlacementRateCardLine new fields and calculation info
> Including changes to PlacementRateCard 

- source/includes/_services.md
The http verb for issue report service was incorrect
> update HTTP verb for issue report

- source/includes/_services.md
This PR adds documentation for the batchExportStatus service endpoint.
> feat(docs): add batchExportStatus documentation

- source/includes/entityref/paybill/_calendar.md
- source/includes/entityref/paybill/_calendarinstance.md
- source/includes/entityref/paybill/_paybillcycle.md
Update documentation for Pay Bill Cycle and Calendar
> BH-74712 update payBillCycle and calendar documentation

- source/entityref.html.md
- source/includes/entityref/_candidateavailability.md
- source/includes/entityref/_candidateshiftpreference.md
- source/includes/entityref/_jobshift.md
- source/includes/entityref/_jobshiftassignment.md
- source/includes/entityref/_jobshiftsubmission.md
- source/includes/entityref/_note.md
- source/includes/entityref/_shift.md
- source/includes/entityref/_shiftposition.md
- source/includes/entityref/_shifttype.md
Closes out [BH-74372](https://jira.bullhorn.com/browse/BH-74372)
Added API docs for shifts related entities and updated the Notes entity with new fields
Shift (shift definition)
ShiftPosition
JobShift
CandidateAvailability
CandidatePreferences
ShiftType
JobShiftSubmission
JobShiftAssignment
Note (add JobShifts as an entity reference)
> Updating Shifts API Docs

- source/includes/entityref/_placement.md
Adding BTE Sync Status and BTE Last Sync Date fields to Placement entity documentation per [BH-76522](https://jira.bullhorn.com/browse/BH-76522)
> Add new BTE fields to placement entity reference

- source/includes/entityref/_candidate.md
Code is already merged, just need to update documentation
> Adding documentation for timestamp field restriction

- source/includes/entityref/_candidatecertification.md
- source/includes/entityref/_certification.md
Previously, this field's description was blank. We are updating dateAdded to have a description like other dateAdded fields.
> BH-77882 - Adding description to DateAdded field for Certifications.

- source/includes/entityref/_deduction.md
- source/includes/entityref/_employeepay.md
- source/includes/entityref/_employeetaxdeduction.md
- source/includes/entityref/_employercontribution.md
- source/includes/entityref/_paycheck.md
- source/includes/entityref/paybill/_deductioncategorylookup.md
Rest documentation for the paycheck visibility entities.
> BH-78250 Paycheck Visibility REST API Documentation 

- source/includes/entityref/paybill/_clientcorporationrateagreementcard.md
- source/includes/entityref/paybill/_clientcorporationrateagreementcardline.md
- source/includes/entityref/paybill/_clientcorporationrateagreementcardlinegroup.md
- source/includes/entityref/paybill/_clientcorporationrateagreementcardversion.md
add documentation for new entities
> *DO NOT MERGE* BH-77097: Add REST API documentation to github for Client Rate Agreements *DO NOT MERGE*

- source/includes/article/_gettingstartedrest.md
Update rest docs with east urls
> Update rest docs with east urls

- source/entityref.html.md
add client corp rate cards to entity list
> BH-77097: add client corp rate cards to entity list

- source/includes/entityref/_joborder.md
- source/includes/entityref/_placement.md
- Adding jobLocation, location, and owner to Placement entity
- Updating description for owner on Placement and Job to note that the field map name will be userID/jobUserID
> Updating documentation for Placement and JobOrder

- source/includes/entityref/_workerscompensation.md
- source/includes/entityref/_workerscompensationrate.md
This adds dateAdded and dateLastModified fields to Workers Compensation and Workers Compensation Rate entities.
> Add dateAdded and dateLastModified to WorkersComp entities

- source/entityref.html.md
- source/includes/changelog/changelog.md
- source/includes/entityref/paybill/_accountingperiod.md
- source/includes/entityref/paybill/_billablecharge.md
- source/includes/entityref/paybill/_billmastertransaction.md
- source/includes/entityref/paybill/_payablecharge.md
- source/includes/entityref/paybill/_paymastertransaction.md
With the work of the accounting period feature we created a new entity and made some changes to existing pay and bill entities. Documentation has been updated to reflect these changes.
> Adding Accounting Period feature documentation

- source/includes/changelog/changelog.md
- source/includes/entityref/paybill/_timesheetentry.md
> Prerelease 2024.08

- source/includes/entityref/_category.md
- source/includes/entityref/_specialty.md
Modified the REST API documentation to accurately match the SOAP documentation regarding read-only fields.
> BH-80957 Modified the REST API documentation

- source/includes/changelog/changelog.md
- source/includes/entityref/paybill/_directdepositaccount.md
Add new field to DirectDepositAccount (allocationMethod)
> BH-90237 add new allocationMethod field for DirectDepositAccount

- source/includes/_services.md
- source/includes/changelog/changelog.md
- source/includes/entityref/paybill/_billmaster.md
Adds two entries, one each for PUT and POST calls to the Billable Charge service.
> BH-87563 - Add documentation for billable charge service endpoint

- source/includes/_authorization.md
Updating documentation based on token formatting.
- Query parameters only accept B**h**RestToken:
- HTTP header accepts both B**h**RestToken and B**H**RestToken:
- Cookies only accept B**h**RestToken
> f/BH-90196 Updating token formatting

- source/includes/changelog/changelog.md
- source/includes/entityref/paybill/_invoiceterm.md
- source/includes/entityref/paybill/_invoicetermversion.md
Adding fields for flexible invoicing to invoiceTerm and invoiceTermVersion
> Adding new fields to invoiceterm and invoicetermversion
